// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#ifndef _CLOCK_ESP32_UI_H
#define _CLOCK_ESP32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_thermometer_30_png);   // assets/thermometer_30.png
LV_IMG_DECLARE( ui_img_1191103926);   // assets/water-percent_30.png
LV_IMG_DECLARE( ui_img_00d_64_png);   // assets/00d_64.png
LV_IMG_DECLARE( ui_img_00n_64_png);   // assets/00n_64.png
LV_IMG_DECLARE( ui_img_01d_64_png);   // assets/01d_64.png
LV_IMG_DECLARE( ui_img_01n_64_png);   // assets/01n_64.png
LV_IMG_DECLARE( ui_img_02_64_png);   // assets/02_64.png
LV_IMG_DECLARE( ui_img_03_64_png);   // assets/03_64.png
LV_IMG_DECLARE( ui_img_45_64_png);   // assets/45_64.png
LV_IMG_DECLARE( ui_img_48_64_png);   // assets/48_64.png
LV_IMG_DECLARE( ui_img_51_63d_64_png);   // assets/51_63d_64.png
LV_IMG_DECLARE( ui_img_51_63n_64_png);   // assets/51_63n_64.png
LV_IMG_DECLARE( ui_img_65_64_png);   // assets/65_64.png
LV_IMG_DECLARE( ui_img_66_67_96_99_64_png);   // assets/66_67_96_99_64.png
LV_IMG_DECLARE( ui_img_71d_64_png);   // assets/71d_64.png
LV_IMG_DECLARE( ui_img_71n_64_png);   // assets/71n_64.png
LV_IMG_DECLARE( ui_img_73_77_64_png);   // assets/73_77_64.png
LV_IMG_DECLARE( ui_img_80_82_64_png);   // assets/80_82_64.png
LV_IMG_DECLARE( ui_img_85_86_64_png);   // assets/85_86_64.png
LV_IMG_DECLARE( ui_img_95_64_png);   // assets/95_64.png

// FONTS
LV_FONT_DECLARE( ui_font_dsdigital128);
LV_FONT_DECLARE( ui_font_dsdigital48);
LV_FONT_DECLARE( ui_font_roboto20);
LV_FONT_DECLARE( ui_font_roboto32);
LV_FONT_DECLARE( ui_font_roboto36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
