// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#ifndef _CLOCK_ESP32_UI_H
#define _CLOCK_ESP32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_thermometer_30_png);   // assets/thermometer_30.png
LV_IMG_DECLARE( ui_img_1191103926);   // assets/water-percent_30.png
LV_IMG_DECLARE( ui_img_00d_75_png);   // assets/00d_75.png
LV_IMG_DECLARE( ui_img_00n_75_png);   // assets/00n_75.png
LV_IMG_DECLARE( ui_img_01d_75_png);   // assets/01d_75.png
LV_IMG_DECLARE( ui_img_01n_75_png);   // assets/01n_75.png
LV_IMG_DECLARE( ui_img_02_75_png);   // assets/02_75.png
LV_IMG_DECLARE( ui_img_03_75_png);   // assets/03_75.png
LV_IMG_DECLARE( ui_img_45_75_png);   // assets/45_75.png
LV_IMG_DECLARE( ui_img_48_75_png);   // assets/48_75.png
LV_IMG_DECLARE( ui_img_51_55_61_75_png);   // assets/51_55_61_75.png
LV_IMG_DECLARE( ui_img_56_57_66_67_75_png);   // assets/56_57_66_67_75.png
LV_IMG_DECLARE( ui_img_63_75_png);   // assets/63_75.png
LV_IMG_DECLARE( ui_img_65_80_82_75_png);   // assets/65_80_82_75.png
LV_IMG_DECLARE( ui_img_85_86_75_png);   // assets/85_86_75.png
LV_IMG_DECLARE( ui_img_95_75_png);   // assets/95_75.png
LV_IMG_DECLARE( ui_img_96_99_75_png);   // assets/96_99_75.png
LV_IMG_DECLARE( ui_img_71_77_75_png);   // assets/71_77_75.png

// FONTS
LV_FONT_DECLARE( ui_font_dsdigital128);
LV_FONT_DECLARE( ui_font_dsdigital48);
LV_FONT_DECLARE( ui_font_roboto20);
LV_FONT_DECLARE( ui_font_roboto32);
LV_FONT_DECLARE( ui_font_roboto36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
