// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#ifndef _CLOCK_ESP32_UI_H
#define _CLOCK_ESP32_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_thermometer_30_png);   // assets/thermometer_30.png
LV_IMG_DECLARE( ui_img_1191103926);   // assets/water-percent_30.png
LV_IMG_DECLARE( ui_img_01d_64_png);   // assets/01d_64.png
LV_IMG_DECLARE( ui_img_01n_64_png);   // assets/01n_64.png
LV_IMG_DECLARE( ui_img_02d_64_png);   // assets/02d_64.png
LV_IMG_DECLARE( ui_img_02n_64_png);   // assets/02n_64.png
LV_IMG_DECLARE( ui_img_03d_64_png);   // assets/03d_64.png
LV_IMG_DECLARE( ui_img_04d_64_png);   // assets/04d_64.png
LV_IMG_DECLARE( ui_img_09d_64_png);   // assets/09d_64.png
LV_IMG_DECLARE( ui_img_10d_64_png);   // assets/10d_64.png
LV_IMG_DECLARE( ui_img_10n_64_png);   // assets/10n_64.png
LV_IMG_DECLARE( ui_img_11d_64_png);   // assets/11d_64.png
LV_IMG_DECLARE( ui_img_11n_64_png);   // assets/11n_64.png
LV_IMG_DECLARE( ui_img_13d_64_png);   // assets/13d_64.png
LV_IMG_DECLARE( ui_img_13n_64_png);   // assets/13n_64.png
LV_IMG_DECLARE( ui_img_50d_64_png);   // assets/50d_64.png
LV_IMG_DECLARE( ui_img_10_64_png);   // assets/10_64.png
LV_IMG_DECLARE( ui_img_13_64_png);   // assets/13_64.png
LV_IMG_DECLARE( ui_img_11_64_png);   // assets/11_64.png
LV_IMG_DECLARE( ui_img_1142085373);   // assets/clear-day.png
LV_IMG_DECLARE( ui_img_1774994173);   // assets/clear-night.png
LV_IMG_DECLARE( ui_img_drizzle_png);   // assets/drizzle.png
LV_IMG_DECLARE( ui_img_120377083);   // assets/extreme-day-rain.png
LV_IMG_DECLARE( ui_img_1522742772);   // assets/extreme-day-snow.png
LV_IMG_DECLARE( ui_img_300219483);   // assets/extreme-night-rain.png
LV_IMG_DECLARE( ui_img_1342629780);   // assets/extreme-night-snow.png
LV_IMG_DECLARE( ui_img_102872400);   // assets/extreme-rain.png
LV_IMG_DECLARE( ui_img_1533765271);   // assets/extreme-snow.png
LV_IMG_DECLARE( ui_img_459294810);   // assets/fog-day.png
LV_IMG_DECLARE( ui_img_834737478);   // assets/fog-night.png
LV_IMG_DECLARE( ui_img_fog_png);   // assets/fog.png
LV_IMG_DECLARE( ui_img_1190589243);   // assets/overcast-day.png
LV_IMG_DECLARE( ui_img_1009007355);   // assets/overcast-night.png
LV_IMG_DECLARE( ui_img_1816698321);   // assets/overcast-rain.png
LV_IMG_DECLARE( ui_img_990123390);   // assets/overcast-snow.png
LV_IMG_DECLARE( ui_img_overcast_png);   // assets/overcast.png
LV_IMG_DECLARE( ui_img_1937960972);   // assets/partly-cloudy-day-drizzle.png
LV_IMG_DECLARE( ui_img_1181745046);   // assets/partly-cloudy-day-rain.png
LV_IMG_DECLARE( ui_img_454646321);   // assets/partly-cloudy-day-snow.png
LV_IMG_DECLARE( ui_img_860055119);   // assets/partly-cloudy-day.png
LV_IMG_DECLARE( ui_img_1618810380);   // assets/partly-cloudy-night-drizzle.png
LV_IMG_DECLARE( ui_img_2139431338);   // assets/partly-cloudy-night-rain.png
LV_IMG_DECLARE( ui_img_544304527);   // assets/partly-cloudy-night-snow.png
LV_IMG_DECLARE( ui_img_1722154033);   // assets/partly-cloudy-night.png
LV_IMG_DECLARE( ui_img_rain_png);   // assets/rain.png
LV_IMG_DECLARE( ui_img_sleet_png);   // assets/sleet.png
LV_IMG_DECLARE( ui_img_snow_png);   // assets/snow.png
LV_IMG_DECLARE( ui_img_1589909526);   // assets/thunderstorms-day-extreme-rain.png
LV_IMG_DECLARE( ui_img_1968872656);   // assets/thunderstorms-day-overcast-snow.png
LV_IMG_DECLARE( ui_img_980277765);   // assets/thunderstorms-day-rain.png
LV_IMG_DECLARE( ui_img_1041458778);   // assets/thunderstorms-day.png
LV_IMG_DECLARE( ui_img_265942921);   // assets/thunderstorms-extreme-rain.png
LV_IMG_DECLARE( ui_img_683190538);   // assets/thunderstorms-night-extreme-rain.png
LV_IMG_DECLARE( ui_img_1483411600);   // assets/thunderstorms-night-overcast-snow.png
LV_IMG_DECLARE( ui_img_235723173);   // assets/thunderstorms-night-rain.png
LV_IMG_DECLARE( ui_img_1963032070);   // assets/thunderstorms-night.png
LV_IMG_DECLARE( ui_img_2024358586);   // assets/thunderstorms-overcast-rain.png
LV_IMG_DECLARE( ui_img_1367567803);   // assets/thunderstorms-overcast-snow.png
LV_IMG_DECLARE( ui_img_175543064);   // assets/thunderstorms-rain.png
LV_IMG_DECLARE( ui_img_thunderstorms_png);   // assets/thunderstorms.png

// FONTS
LV_FONT_DECLARE( ui_font_dsdigital128);
LV_FONT_DECLARE( ui_font_dsdigital48);
LV_FONT_DECLARE( ui_font_roboto20);
LV_FONT_DECLARE( ui_font_roboto32);
LV_FONT_DECLARE( ui_font_roboto36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
