// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_uiLabelTime1 = NULL;lv_obj_t *ui_uiLabelDate1 = NULL;lv_obj_t *ui_uiLabelDay1 = NULL;lv_obj_t *ui_uiLabelTemp1 = NULL;lv_obj_t *ui_uiLabelHumidity1 = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_uiLabelWeather = NULL;lv_obj_t *ui_WiFiStatus = NULL;lv_obj_t *ui_Image00d = NULL;lv_obj_t *ui_Image00n = NULL;lv_obj_t *ui_Image01d = NULL;lv_obj_t *ui_Image01n = NULL;lv_obj_t *ui_Image02 = NULL;lv_obj_t *ui_Image03 = NULL;lv_obj_t *ui_Image45 = NULL;lv_obj_t *ui_Image48 = NULL;lv_obj_t *ui_Image515561 = NULL;lv_obj_t *ui_Image56576667 = NULL;lv_obj_t *ui_Image63 = NULL;lv_obj_t *ui_Image658082 = NULL;lv_obj_t *ui_Image8586 = NULL;lv_obj_t *ui_Image95 = NULL;lv_obj_t *ui_Image9699 = NULL;lv_obj_t *ui_Image7177 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uiLabelTime1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelTime1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTime1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTime1, -3 );
lv_obj_set_y( ui_uiLabelTime1, -59 );
lv_obj_set_align( ui_uiLabelTime1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelTime1,"");
lv_obj_set_style_text_color(ui_uiLabelTime1, lv_color_hex(0xF4FE23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelTime1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_uiLabelTime1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelTime1, &ui_font_dsdigital128, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelDate1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelDate1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDate1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDate1, 0 );
lv_obj_set_y( ui_uiLabelDate1, 15 );
lv_obj_set_align( ui_uiLabelDate1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelDate1,"");
lv_obj_set_style_text_color(ui_uiLabelDate1, lv_color_hex(0x00FFA8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelDate1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelDate1, &ui_font_dsdigital48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelDay1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelDay1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDay1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDay1, 125 );
lv_obj_set_y( ui_uiLabelDay1, 81 );
lv_obj_set_align( ui_uiLabelDay1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelDay1,"");
lv_obj_set_style_text_color(ui_uiLabelDay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelDay1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelDay1, &ui_font_roboto36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelTemp1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelTemp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTemp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTemp1, 135 );
lv_obj_set_y( ui_uiLabelTemp1, 61 );
lv_obj_set_align( ui_uiLabelTemp1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelTemp1,"");
lv_obj_set_style_text_color(ui_uiLabelTemp1, lv_color_hex(0xFFF65E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelTemp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelTemp1, &ui_font_roboto32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelHumidity1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelHumidity1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelHumidity1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelHumidity1, 140 );
lv_obj_set_y( ui_uiLabelHumidity1, 97 );
lv_obj_set_align( ui_uiLabelHumidity1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelHumidity1,"");
lv_obj_set_style_text_color(ui_uiLabelHumidity1, lv_color_hex(0x88E4FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelHumidity1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelHumidity1, &ui_font_roboto32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_thermometer_30_png);
lv_obj_set_width( ui_Image4, 30);
lv_obj_set_height( ui_Image4, 30);
lv_obj_set_x( ui_Image4, -39 );
lv_obj_set_y( ui_Image4, 61 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,300);
lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFFF65E), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_1191103926);
lv_obj_set_width( ui_Image5, 30);
lv_obj_set_height( ui_Image5, 30);
lv_obj_set_x( ui_Image5, -39 );
lv_obj_set_y( ui_Image5, 96 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_Image5,10,0);
lv_img_set_zoom(ui_Image5,290);
lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0x88E4FF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_width(ui_Image5, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_width(ui_Image5, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_min_height(ui_Image5, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_max_height(ui_Image5, 30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 431);
lv_obj_set_height( ui_Container2, 28);
lv_obj_set_x( ui_Container2, -57 );
lv_obj_set_y( ui_Container2, 73 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Container2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uiLabelWeather = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelWeather, 75);
lv_obj_set_height( ui_uiLabelWeather, 75);
lv_obj_set_x( ui_uiLabelWeather, -110 );
lv_obj_set_y( ui_uiLabelWeather, 75 );
lv_obj_set_align( ui_uiLabelWeather, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_uiLabelWeather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_uiLabelWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_uiLabelWeather,230);

ui_WiFiStatus = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_WiFiStatus);
lv_obj_set_width( ui_WiFiStatus, 8);
lv_obj_set_height( ui_WiFiStatus, 8);
lv_obj_set_x( ui_WiFiStatus, 152 );
lv_obj_set_y( ui_WiFiStatus, -115 );
lv_obj_set_align( ui_WiFiStatus, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_WiFiStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WiFiStatus, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WiFiStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image00d = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image00d, &ui_img_00d_75_png);
lv_obj_set_width( ui_Image00d, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image00d, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image00d, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image00d, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image00d, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image00n = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image00n, &ui_img_00n_75_png);
lv_obj_set_width( ui_Image00n, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image00n, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image00n, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image00n, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image00n, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image01d = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image01d, &ui_img_01d_75_png);
lv_obj_set_width( ui_Image01d, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image01d, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image01d, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image01d, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image01d, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image01n = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image01n, &ui_img_01n_75_png);
lv_obj_set_width( ui_Image01n, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image01n, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image01n, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image01n, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image01n, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image02 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image02, &ui_img_02_75_png);
lv_obj_set_width( ui_Image02, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image02, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image02, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image02, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image02, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image03 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image03, &ui_img_03_75_png);
lv_obj_set_width( ui_Image03, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image03, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image03, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image03, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image03, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image45 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image45, &ui_img_45_75_png);
lv_obj_set_width( ui_Image45, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image45, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image45, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image45, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image45, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image48 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image48, &ui_img_48_75_png);
lv_obj_set_width( ui_Image48, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image48, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image48, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image48, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image48, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image515561 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image515561, &ui_img_51_55_61_75_png);
lv_obj_set_width( ui_Image515561, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image515561, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image515561, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image515561, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image515561, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image56576667 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image56576667, &ui_img_56_57_66_67_75_png);
lv_obj_set_width( ui_Image56576667, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image56576667, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image56576667, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image56576667, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image56576667, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image63 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image63, &ui_img_63_75_png);
lv_obj_set_width( ui_Image63, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image63, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image63, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image63, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image63, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image658082 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image658082, &ui_img_65_80_82_75_png);
lv_obj_set_width( ui_Image658082, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image658082, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image658082, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image658082, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image658082, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8586 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image8586, &ui_img_85_86_75_png);
lv_obj_set_width( ui_Image8586, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image8586, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image8586, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8586, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8586, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image95 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image95, &ui_img_95_75_png);
lv_obj_set_width( ui_Image95, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image95, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image95, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image95, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image95, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9699 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image9699, &ui_img_96_99_75_png);
lv_obj_set_width( ui_Image9699, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image9699, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image9699, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9699, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9699, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image7177 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image7177, &ui_img_71_77_75_png);
lv_obj_set_width( ui_Image7177, LV_SIZE_CONTENT);  /// 75
lv_obj_set_height( ui_Image7177, LV_SIZE_CONTENT);   /// 75
lv_obj_set_align( ui_Image7177, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7177, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7177, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_uiLabelTime1= NULL;
ui_uiLabelDate1= NULL;
ui_uiLabelDay1= NULL;
ui_uiLabelTemp1= NULL;
ui_uiLabelHumidity1= NULL;
ui_Image4= NULL;
ui_Image5= NULL;
ui_Container2= NULL;
ui_uiLabelWeather= NULL;
ui_WiFiStatus= NULL;
ui_Image00d= NULL;
ui_Image00n= NULL;
ui_Image01d= NULL;
ui_Image01n= NULL;
ui_Image02= NULL;
ui_Image03= NULL;
ui_Image45= NULL;
ui_Image48= NULL;
ui_Image515561= NULL;
ui_Image56576667= NULL;
ui_Image63= NULL;
ui_Image658082= NULL;
ui_Image8586= NULL;
ui_Image95= NULL;
ui_Image9699= NULL;
ui_Image7177= NULL;

}
