// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_uiLabelTime1;
extern lv_obj_t *ui_uiLabelDate1;
extern lv_obj_t *ui_uiLabelDay1;
extern lv_obj_t *ui_uiLabelTemp1;
extern lv_obj_t *ui_uiLabelHumidity1;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_uiLabelWeather;
extern lv_obj_t *ui_WiFiStatus;
extern lv_obj_t *ui_Image00d;
extern lv_obj_t *ui_Image00n;
extern lv_obj_t *ui_Image01d;
extern lv_obj_t *ui_Image01n;
extern lv_obj_t *ui_Image02;
extern lv_obj_t *ui_Image03;
extern lv_obj_t *ui_Image45;
extern lv_obj_t *ui_Image48;
extern lv_obj_t *ui_Image5163d;
extern lv_obj_t *ui_Image5163n;
extern lv_obj_t *ui_Image65;
extern lv_obj_t *ui_Image66679699;
extern lv_obj_t *ui_Image71d;
extern lv_obj_t *ui_Image71n;
extern lv_obj_t *ui_Image7377;
extern lv_obj_t *ui_Image8082;
extern lv_obj_t *ui_Image8586;
extern lv_obj_t *ui_Image95;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

