// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_uiLabelTime1;
extern lv_obj_t *ui_uiLabelDate1;
extern lv_obj_t *ui_uiLabelDay1;
extern lv_obj_t *ui_uiLabelTemp1;
extern lv_obj_t *ui_uiLabelHumidity1;
extern lv_obj_t *ui_uiLabelPressure1;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_uiLabelWeather;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Image28;
extern lv_obj_t *ui_Image29;
extern lv_obj_t *ui_Image30;
extern lv_obj_t *ui_Image31;
extern lv_obj_t *ui_Image32;
extern lv_obj_t *ui_Image33;
extern lv_obj_t *ui_Image34;
extern lv_obj_t *ui_Image35;
extern lv_obj_t *ui_Image36;
extern lv_obj_t *ui_Image37;
extern lv_obj_t *ui_Image38;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_WiFiStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

