[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; lib_archive = no требуется для корректной линковки некоторых версий LVGL
lib_archive = no

; Подключаем скрипты:
extra_scripts = 
    pre:pio_tools.py

build_flags = 
    ; Настройки LVGL
    -D LV_CONF_INCLUDE_SIMPLE
    -I src
    -I include
    -I lib/ui
    
    ; Настройки драйвера дисплея TFT_eSPI
    -D USER_SETUP_LOADED
    -D ST7789_DRIVER
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_INVERSION_OFF
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=27
    -D TFT_RST=33
    -D TFT_BL=22
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD
    -D LOAD_FONT2
    -D LOAD_FONT4
    -D LOAD_FONT6
    -D LOAD_FONT7
    -D LOAD_FONT8
    -D LOAD_GFXFF
    -D SMOOTH_FONT
    -D SPI_FREQUENCY=80000000

    ; Настройки тачскрина XPT2046
    -D TOUCH_CS=14
    -D TOUCH_CLK=12
    -D TOUCH_MISO=13
    -D TOUCH_MOSI=15

lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    lvgl/lvgl@8.3.11
    bblanchon/ArduinoJson@^7.0.4

; Настройки памяти Flash (8MB согласно твоему конфигу)
board_build.flash_mode = qio
board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB

; --- СЕКЦИЯ ПРОШИВКИ (USB) ---
; upload_protocol = esptool
; upload_port = /dev/cu.usbserial-110
; upload_speed = 460800

; --- СЕКЦИЯ ПРОШИВКИ (OTA) ---
; Настройки прошивки по воздуху (OTA)
upload_protocol = espota
upload_port = Clock-ESP32.local
