// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TFT_Arduino

#ifndef _TFT_ARDUINO_UI_H
#define _TFT_ARDUINO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1605233879);   // assets/thermometer-custom.png
LV_IMG_DECLARE( ui_img_1620110196);   // assets/water-percent-custom.png
LV_IMG_DECLARE( ui_img_463316836);   // assets/gauge-custom.png

// FONTS
LV_FONT_DECLARE( ui_font_DSEG7100);
LV_FONT_DECLARE( ui_font_DSEG780);
LV_FONT_DECLARE( ui_font_DSEG788);
LV_FONT_DECLARE( ui_font_DSEG794);
LV_FONT_DECLARE( ui_font_digital24);
LV_FONT_DECLARE( ui_font_digital48);
LV_FONT_DECLARE( ui_font_dsdigital120);
LV_FONT_DECLARE( ui_font_dsdigital128);
LV_FONT_DECLARE( ui_font_dsdigital48);
LV_FONT_DECLARE( ui_font_dsdigital64);
LV_FONT_DECLARE( ui_font_dsdigital72);
LV_FONT_DECLARE( ui_font_dsdigital96);
LV_FONT_DECLARE( ui_font_roboto24);
LV_FONT_DECLARE( ui_font_roboto48);
LV_FONT_DECLARE( ui_font_roboto64);
LV_FONT_DECLARE( ui_font_dsdigital24);
LV_FONT_DECLARE( ui_font_dsdigital32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
