// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_uiLabelTime = NULL;lv_obj_t *ui_uiLabelDate = NULL;lv_obj_t *ui_uiLabelMonth = NULL;lv_obj_t *ui_uiLabelYear = NULL;lv_obj_t *ui_uiLabelDay = NULL;lv_obj_t *ui_uiLabelTemp = NULL;lv_obj_t *ui_uiLabelHumidity = NULL;lv_obj_t *ui_uiLabelPressure = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Image3 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Panel3 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uiLabelTime = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTime, -4 );
lv_obj_set_y( ui_uiLabelTime, -80 );
lv_obj_set_align( ui_uiLabelTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelTime,"--:--");
lv_obj_set_style_text_color(ui_uiLabelTime, lv_color_hex(0xEFFB03), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_uiLabelTime, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelTime, &ui_font_DSEG780, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelDate = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDate, -55 );
lv_obj_set_y( ui_uiLabelDate, -15 );
lv_obj_set_align( ui_uiLabelDate, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelDate,"--");
lv_obj_set_style_text_color(ui_uiLabelDate, lv_color_hex(0xFE88FC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelDate, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelDate, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelMonth = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelMonth, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelMonth, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelMonth, 20 );
lv_obj_set_y( ui_uiLabelMonth, -15 );
lv_obj_set_align( ui_uiLabelMonth, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelMonth,"---------");
lv_obj_set_style_text_color(ui_uiLabelMonth, lv_color_hex(0xFE88FC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelMonth, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelMonth, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelYear = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelYear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelYear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelYear, 90 );
lv_obj_set_y( ui_uiLabelYear, 40 );
lv_obj_set_align( ui_uiLabelYear, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelYear,"----");
lv_obj_set_style_text_color(ui_uiLabelYear, lv_color_hex(0x94E757), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelYear, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelYear, &ui_font_roboto48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelDay = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDay, 95 );
lv_obj_set_y( ui_uiLabelDay, 85 );
lv_obj_set_align( ui_uiLabelDay, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelDay,"--");
lv_obj_set_style_text_color(ui_uiLabelDay, lv_color_hex(0xD6E175), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelDay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelDay, &ui_font_roboto48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelTemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTemp, 40 );
lv_obj_set_y( ui_uiLabelTemp, 32 );
lv_obj_set_align( ui_uiLabelTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelTemp,"--°С");
lv_obj_set_style_text_color(ui_uiLabelTemp, lv_color_hex(0xFCED00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelTemp, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelHumidity = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelHumidity, 40 );
lv_obj_set_y( ui_uiLabelHumidity, 63 );
lv_obj_set_align( ui_uiLabelHumidity, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelHumidity,"--%");
lv_obj_set_style_text_color(ui_uiLabelHumidity, lv_color_hex(0x66D9FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelHumidity, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelPressure = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelPressure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelPressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelPressure, 40 );
lv_obj_set_y( ui_uiLabelPressure, 95 );
lv_obj_set_align( ui_uiLabelPressure, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelPressure,"---mm");
lv_obj_set_style_text_color(ui_uiLabelPressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelPressure, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -1 );
lv_obj_set_y( ui_Label6, -68 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"14:33");
lv_obj_add_flag( ui_Label6, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_Label6, &ui_font_dsdigital72, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1605233879);
lv_obj_set_width( ui_Image1, 24);
lv_obj_set_height( ui_Image1, 24);
lv_obj_set_x( ui_Image1, -140 );
lv_obj_set_y( ui_Image1, 32 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_Image1,100,100);
lv_obj_set_style_img_recolor(ui_Image1, lv_color_hex(0xFCED00), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_1620110196);
lv_obj_set_width( ui_Image2, 24);
lv_obj_set_height( ui_Image2, 24);
lv_obj_set_x( ui_Image2, -140 );
lv_obj_set_y( ui_Image2, 63 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image2, lv_color_hex(0x66D9FA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image3, &ui_img_463316836);
lv_obj_set_width( ui_Image3, 24);
lv_obj_set_height( ui_Image3, 24);
lv_obj_set_x( ui_Image3, -140 );
lv_obj_set_y( ui_Image3, 95 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 320);
lv_obj_set_height( ui_Panel1, 3);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -35 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xEFE9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 320);
lv_obj_set_height( ui_Panel2, 3);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, 7 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xEFE9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 3);
lv_obj_set_height( ui_Panel3, 113);
lv_obj_set_x( ui_Panel3, 16 );
lv_obj_set_y( ui_Panel3, 0 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xEFE9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_uiLabelTime= NULL;
ui_uiLabelDate= NULL;
ui_uiLabelMonth= NULL;
ui_uiLabelYear= NULL;
ui_uiLabelDay= NULL;
ui_uiLabelTemp= NULL;
ui_uiLabelHumidity= NULL;
ui_uiLabelPressure= NULL;
ui_Label6= NULL;
ui_Image1= NULL;
ui_Image2= NULL;
ui_Image3= NULL;
ui_Panel1= NULL;
ui_Panel2= NULL;
ui_Panel3= NULL;

}
