// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_uiLabelTime;
extern lv_obj_t *ui_uiLabelDate;
extern lv_obj_t *ui_uiLabelMonth;
extern lv_obj_t *ui_uiLabelYear;
extern lv_obj_t *ui_uiLabelDay;
extern lv_obj_t *ui_uiLabelTemp;
extern lv_obj_t *ui_uiLabelHumidity;
extern lv_obj_t *ui_uiLabelPressure;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

