// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TFT_Arduino

#ifndef _TFT_ARDUINO_UI_H
#define _TFT_ARDUINO_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1605233879);   // assets/thermometer-custom.png
LV_IMG_DECLARE( ui_img_1620110196);   // assets/water-percent-custom.png
LV_IMG_DECLARE( ui_img_463316836);   // assets/gauge-custom.png
LV_IMG_DECLARE( ui_img_1238027437);   // assets/02n@2x.png
LV_IMG_DECLARE( ui_img_1700430416);   // assets/01d@2x.png
LV_IMG_DECLARE( ui_img_1232099950);   // assets/01n@2x.png
LV_IMG_DECLARE( ui_img_1706357903);   // assets/02d@2x.png
LV_IMG_DECLARE( ui_img_1707406414);   // assets/03d@2x.png
LV_IMG_DECLARE( ui_img_1239075948);   // assets/03n@2x.png
LV_IMG_DECLARE( ui_img_1694638229);   // assets/04d@2x.png
LV_IMG_DECLARE( ui_img_1226307763);   // assets/04n@2x.png
LV_IMG_DECLARE( ui_img_1690960472);   // assets/09d@2x.png
LV_IMG_DECLARE( ui_img_1222630006);   // assets/09n@2x.png
LV_IMG_DECLARE( ui_img_1131223562);   // assets/10d@2x.png
LV_IMG_DECLARE( ui_img_1599554028);   // assets/10n@2x.png
LV_IMG_DECLARE( ui_img_1130175051);   // assets/11d@2x.png
LV_IMG_DECLARE( ui_img_1598505517);   // assets/11n@2x.png
LV_IMG_DECLARE( ui_img_1123199053);   // assets/13d@2x.png
LV_IMG_DECLARE( ui_img_1591529519);   // assets/13n@2x.png
LV_IMG_DECLARE( ui_img_1308932194);   // assets/50d@2x.png
LV_IMG_DECLARE( ui_img_840601728);   // assets/50n@2x.png

// FONTS
LV_FONT_DECLARE( ui_font_DSEG7100);
LV_FONT_DECLARE( ui_font_DSEG780);
LV_FONT_DECLARE( ui_font_DSEG788);
LV_FONT_DECLARE( ui_font_DSEG794);
LV_FONT_DECLARE( ui_font_digital24);
LV_FONT_DECLARE( ui_font_digital48);
LV_FONT_DECLARE( ui_font_dsdigital120);
LV_FONT_DECLARE( ui_font_dsdigital128);
LV_FONT_DECLARE( ui_font_dsdigital48);
LV_FONT_DECLARE( ui_font_dsdigital64);
LV_FONT_DECLARE( ui_font_dsdigital72);
LV_FONT_DECLARE( ui_font_dsdigital96);
LV_FONT_DECLARE( ui_font_roboto24);
LV_FONT_DECLARE( ui_font_roboto48);
LV_FONT_DECLARE( ui_font_roboto64);
LV_FONT_DECLARE( ui_font_dsdigital24);
LV_FONT_DECLARE( ui_font_dsdigital32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
