// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Clock_ESP32

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_uiLabelTime1 = NULL;lv_obj_t *ui_uiLabelDate1 = NULL;lv_obj_t *ui_uiLabelMonth1 = NULL;lv_obj_t *ui_uiLabelYear1 = NULL;lv_obj_t *ui_uiLabelDay1 = NULL;lv_obj_t *ui_uiLabelTemp1 = NULL;lv_obj_t *ui_uiLabelHumidity1 = NULL;lv_obj_t *ui_uiLabelPressure1 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Image4 = NULL;lv_obj_t *ui_Image5 = NULL;lv_obj_t *ui_Image6 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_Panel5 = NULL;lv_obj_t *ui_Panel6 = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_uiLabelWeather = NULL;lv_obj_t *ui_Image7 = NULL;lv_obj_t *ui_Image8 = NULL;lv_obj_t *ui_Image9 = NULL;lv_obj_t *ui_Image28 = NULL;lv_obj_t *ui_Image29 = NULL;lv_obj_t *ui_Image30 = NULL;lv_obj_t *ui_Image31 = NULL;lv_obj_t *ui_Image32 = NULL;lv_obj_t *ui_Image33 = NULL;lv_obj_t *ui_Image34 = NULL;lv_obj_t *ui_Image35 = NULL;lv_obj_t *ui_Image36 = NULL;lv_obj_t *ui_Image37 = NULL;lv_obj_t *ui_Image38 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uiLabelTime1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelTime1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTime1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTime1, -3 );
lv_obj_set_y( ui_uiLabelTime1, -60 );
lv_obj_set_align( ui_uiLabelTime1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelTime1,"");
lv_obj_set_style_text_color(ui_uiLabelTime1, lv_color_hex(0xF4FE23), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelTime1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_uiLabelTime1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelTime1, &ui_font_dsdigital128, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelDate1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelDate1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDate1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDate1, -62 );
lv_obj_set_y( ui_uiLabelDate1, 20 );
lv_obj_set_align( ui_uiLabelDate1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelDate1,"");
lv_obj_add_flag( ui_uiLabelDate1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_uiLabelDate1, lv_color_hex(0x00FFA8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelDate1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelDate1, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelMonth1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelMonth1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelMonth1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelMonth1, 0 );
lv_obj_set_y( ui_uiLabelMonth1, 14 );
lv_obj_set_align( ui_uiLabelMonth1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelMonth1,"");
lv_obj_set_style_text_color(ui_uiLabelMonth1, lv_color_hex(0x00FFA8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelMonth1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelMonth1, &ui_font_dsdigital40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelYear1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelYear1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelYear1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelYear1, 101 );
lv_obj_set_y( ui_uiLabelYear1, 20 );
lv_obj_set_align( ui_uiLabelYear1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelYear1,"");
lv_obj_add_flag( ui_uiLabelYear1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_uiLabelYear1, lv_color_hex(0x00FFA8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelYear1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelYear1, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelDay1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelDay1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDay1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDay1, 110 );
lv_obj_set_y( ui_uiLabelDay1, 73 );
lv_obj_set_align( ui_uiLabelDay1, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelDay1,"");
lv_obj_set_style_text_color(ui_uiLabelDay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelDay1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelDay1, &ui_font_roboto36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelTemp1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelTemp1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelTemp1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelTemp1, 148 );
lv_obj_set_y( ui_uiLabelTemp1, 48 );
lv_obj_set_align( ui_uiLabelTemp1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelTemp1,"");
lv_obj_set_style_text_color(ui_uiLabelTemp1, lv_color_hex(0xFCED00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelTemp1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelTemp1, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelHumidity1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelHumidity1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelHumidity1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelHumidity1, 148 );
lv_obj_set_y( ui_uiLabelHumidity1, 78 );
lv_obj_set_align( ui_uiLabelHumidity1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelHumidity1,"");
lv_obj_set_style_text_color(ui_uiLabelHumidity1, lv_color_hex(0x66D9FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelHumidity1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelHumidity1, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelPressure1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelPressure1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelPressure1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelPressure1, 148 );
lv_obj_set_y( ui_uiLabelPressure1, 105 );
lv_obj_set_align( ui_uiLabelPressure1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_uiLabelPressure1,"");
lv_obj_set_style_text_color(ui_uiLabelPressure1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelPressure1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelPressure1, &ui_font_roboto24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -1 );
lv_obj_set_y( ui_Label1, -68 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"");
lv_obj_add_flag( ui_Label1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_Label1, &ui_font_dsdigital72, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image4, &ui_img_1605233879);
lv_obj_set_width( ui_Image4, 24);
lv_obj_set_height( ui_Image4, 24);
lv_obj_set_x( ui_Image4, -37 );
lv_obj_set_y( ui_Image4, 48 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,300);
lv_obj_set_style_img_recolor(ui_Image4, lv_color_hex(0xFCED00), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image5, &ui_img_1620110196);
lv_obj_set_width( ui_Image5, 24);
lv_obj_set_height( ui_Image5, 24);
lv_obj_set_x( ui_Image5, -37 );
lv_obj_set_y( ui_Image5, 78 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,300);
lv_obj_set_style_img_recolor(ui_Image5, lv_color_hex(0x66D9FA), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image6, &ui_img_463316836);
lv_obj_set_width( ui_Image6, 24);
lv_obj_set_height( ui_Image6, 24);
lv_obj_set_x( ui_Image6, -37 );
lv_obj_set_y( ui_Image6, 105 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image6,220);
lv_obj_set_style_img_recolor(ui_Image6, lv_color_hex(0xFFFFFF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_Image6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel4, 320);
lv_obj_set_height( ui_Panel4, 3);
lv_obj_set_x( ui_Panel4, 0 );
lv_obj_set_y( ui_Panel4, -35 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Panel4, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xEFE9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel5, 320);
lv_obj_set_height( ui_Panel5, 3);
lv_obj_set_x( ui_Panel5, 0 );
lv_obj_set_y( ui_Panel5, 7 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Panel5, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0xEFE9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel6, 3);
lv_obj_set_height( ui_Panel6, 113);
lv_obj_set_x( ui_Panel6, 16 );
lv_obj_set_y( ui_Panel6, 0 );
lv_obj_set_align( ui_Panel6, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Panel6, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xE9E9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0xEFE9E9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 431);
lv_obj_set_height( ui_Container2, 28);
lv_obj_set_x( ui_Container2, -57 );
lv_obj_set_y( ui_Container2, 73 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Container2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_uiLabelWeather = lv_img_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelWeather, 64);
lv_obj_set_height( ui_uiLabelWeather, 64);
lv_obj_set_x( ui_uiLabelWeather, -110 );
lv_obj_set_y( ui_uiLabelWeather, 72 );
lv_obj_set_align( ui_uiLabelWeather, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_uiLabelWeather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_uiLabelWeather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_uiLabelWeather,255);

ui_Image7 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image7, &ui_img_01d_64_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image8, &ui_img_01n_64_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_Image8, -108 );
lv_obj_set_y( ui_Image8, 65 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image9, &ui_img_02d_64_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image28 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image28, &ui_img_02n_64_png);
lv_obj_set_width( ui_Image28, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image28, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image28, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image28, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image28, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image29 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image29, &ui_img_03d_64_png);
lv_obj_set_width( ui_Image29, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image29, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image29, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image29, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image29, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image30 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image30, &ui_img_04d_64_png);
lv_obj_set_width( ui_Image30, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image30, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image30, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image30, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image30, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image31 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image31, &ui_img_09d_64_png);
lv_obj_set_width( ui_Image31, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image31, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image31, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image31, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image31, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image32 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image32, &ui_img_10d_64_png);
lv_obj_set_width( ui_Image32, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image32, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image32, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image32, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image32, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image33 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image33, &ui_img_10n_64_png);
lv_obj_set_width( ui_Image33, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image33, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image33, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image33, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image33, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image34 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image34, &ui_img_11d_64_png);
lv_obj_set_width( ui_Image34, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image34, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image34, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image34, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image34, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image35 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image35, &ui_img_11n_64_png);
lv_obj_set_width( ui_Image35, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image35, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image35, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image35, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image35, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image36 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image36, &ui_img_13d_64_png);
lv_obj_set_width( ui_Image36, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image36, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image36, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image36, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image36, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image37 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image37, &ui_img_13n_64_png);
lv_obj_set_width( ui_Image37, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image37, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image37, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image37, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image37, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image38 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image38, &ui_img_50d_64_png);
lv_obj_set_width( ui_Image38, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_Image38, LV_SIZE_CONTENT);   /// 64
lv_obj_set_align( ui_Image38, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image38, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image38, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_uiLabelTime1= NULL;
ui_uiLabelDate1= NULL;
ui_uiLabelMonth1= NULL;
ui_uiLabelYear1= NULL;
ui_uiLabelDay1= NULL;
ui_uiLabelTemp1= NULL;
ui_uiLabelHumidity1= NULL;
ui_uiLabelPressure1= NULL;
ui_Label1= NULL;
ui_Image4= NULL;
ui_Image5= NULL;
ui_Image6= NULL;
ui_Panel4= NULL;
ui_Panel5= NULL;
ui_Panel6= NULL;
ui_Container2= NULL;
ui_uiLabelWeather= NULL;
ui_Image7= NULL;
ui_Image8= NULL;
ui_Image9= NULL;
ui_Image28= NULL;
ui_Image29= NULL;
ui_Image30= NULL;
ui_Image31= NULL;
ui_Image32= NULL;
ui_Image33= NULL;
ui_Image34= NULL;
ui_Image35= NULL;
ui_Image36= NULL;
ui_Image37= NULL;
ui_Image38= NULL;

}
