// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: TFT_Arduino

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_uiLabelTime1;
extern lv_obj_t *ui_uiLabelDate1;
extern lv_obj_t *ui_uiLabelMonth1;
extern lv_obj_t *ui_uiLabelYear1;
extern lv_obj_t *ui_uiLabelDay1;
extern lv_obj_t *ui_uiLabelTemp1;
extern lv_obj_t *ui_uiLabelHumidity1;
extern lv_obj_t *ui_uiLabelPressure1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_uiLabelWeather;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

